### ISSUE TITLE
No hosts file

### ISSUE THREAD

**Issue by miloshake** [eaaasun/CCStopper#102]
### Body

How do I fix this :(

![image_2023-12-16_161621016](https://github.com/eaaasun/CCStopper/assets/90105482/5224b02d-e945-4f06-9a78-0ad77ab10310)

![image_2023-12-16_161717835](https://github.com/eaaasun/CCStopper/assets/90105482/5fd4a961-c6c6-468d-917e-9069652d1a7f)

### Duplicate Issues

- [X] I have read through the issues and have not found a duplicate.

**Comment by eaaasun** [comment]
Looks like the hosts file is missing, you can just create a file without an extension named `hosts` and paste what was in `hosts.backup` into it.
