### ISSUE TITLE
[Bug]: Creative Cloud crashes after applying credit card patch ("start trial")

### ISSUE THREAD

**Issue by BrightDarknessXX** [eaaasun/CCStopper#103]
### What happened?

I opened CCSTOPPER v1.2.3-hotfix.2 > [3] System Patches \ [1] Creative Cloud App
because it asks me to put credit card information in for downloading an app.

When I start Creative Cloud Desktop, it shows that it's initializing creative cloud. After a while, it crashes and wants to re-install itself.

### Expected Result?

Creative Cloud starts up normally and allows me to download its apps.

### Version?

v1.2.3-hotfix.2

### How did you use CCStopper?

One-Line - Run

### Windows Version?

Windows 10 22H2

### Duplicate Issues

- [X] I have read through the issues and have not found a duplicate.

**Comment by t4rra** [comment]
[CCStopper is being sunset.](https://github.com/eaaasun/CCStopper#migrating-fromuninstalling-ccstopper-) Please see #91.
