### ISSUE TITLE
ERROR: The process "AGSService.exe" not found

### ISSUE THREAD

**Issue by Steveng703** [eaaasun/CCStopper#19]
### What happened?

Whenever I do option 2, Remove Genuine Checker.  Another cmd flashes for a second before closing.  By taking a screen recording, I was able to see what the 2nd instance of cmd says:

![image](https://user-images.githubusercontent.com/104599216/165851402-4eb3924a-f91e-441b-a28f-c73efcf26174.png)

It's a fresh install of Adobe Creative Cloud, so I don't think the issue is on that end.

Apologies if I've just done something wrong, I'm new to the world of editing adobe files that I have 100% legally purchased

**Comment by ItsProfessional** [comment]
This just means the "AGSService" service wasn't running for some reason when you ran the script. This is fine as if it were running, the script would stop it...
So this can be closed
