### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by TheColin21** [eaaasun/CCStopper#3]
The current way of calling the scripts from the scripts subfolder does not work if the main Batch-file is executed from somewhere else than the directory the scripts subfolder is in. It would probably be easiest to cd to the directory where the main BAT lies at the beginning of the script.

**Comment by ItsProfessional** [comment]
A pull request I created fixed this and it is merged in the development branch. This issue can be closed when the development branch is merged to the main branch.
