### ISSUE TITLE
[Bug]: Internet Block doesnt work

### ISSUE THREAD

**Issue by dropouut** [eaaasun/CCStopper#40]
### What happened?

if i run Internet Block it says: ERROR Permission Denied

**Comment by eaaasun** [comment]
Did you run the script as admin? If not, try doing that, but if so, your permissions to the file might be read-only. You'll need to give yourself write access to the hosts file.

**Comment by dropouut** [comment]
> Did you run the script as admin? If not, try doing that, but if so, your permissions to the file might be read-only. You'll need to give yourself write access to the hosts file.

I found out why, it was my antivirus. the programm is running internetblock and adds the addresses to the hosts file. but when i start Adobe Creative Cloud it says: Access Limited to Adobe Application and still dont work

**Comment by ItsProfessional** [comment]
I also got the "limited access" notification, but you can ignore that. everything *should* work regardless of that notification.

**Comment by dropouut** [comment]
> I also got the "limited access" notification, but you can ignore that. everything _should_ work regardless of that notification.


if i press "Try out" it is just showing the prompt and not working

**Comment by ItsProfessional** [comment]
> > I also got the "limited access" notification, but you can ignore that. everything _should_ work regardless of that notification.
> 
> if i press "Try out" it is just showing the prompt and not working

When you apply the internetblock patch does it say "Firewall rule exists!"?

**Comment by dropouut** [comment]
> 

I have Kaspersky Total Security, and they have a firewall

**Comment by dropouut** [comment]
> > > I also got the "limited access" notification, but you can ignore that. everything _should_ work regardless of that notification.
> > 
> > 
> > if i press "Try out" it is just showing the prompt and not working
> 
> When you apply the internetblock patch does it say "Firewall rule exists!"?
> 
> Edit: Since you have a third party antivirus installed, it's possibly that your antivirus has its own firewall and it disabled the windows defender firewall. You can try adding the rule manually in your antivirus firewall

It is working, i disabled Program control and firewall
