### ISSUE TITLE
[Bug]: Internet block does not work if hosts file is not empty

### ISSUE THREAD

**Issue by azumukupoe** [eaaasun/CCStopper#44]
### What happened?

I already use unchecky and https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate which adds quite a lot of lines to the hosts file
CCStopper returns error and won't append the rules to the file
also, InternetBlock.bat closes itself when the hosts file is read only

**Comment by eaaasun** [comment]
Should be fixed with the rewrite of the internetblock (now hostblock) module, will close once 1.2.0 is finished.
