### ISSUE TITLE
Internet block should redirect to 0.0.0.0 instead of 127.0.0.1

### ISSUE THREAD

**Issue by ImportTaste** [eaaasun/CCStopper#45]
CCStopper should redirect to 0.0.0.0 instead of 127.0.0.1

[Better to block a host to 0.0.0.0 than to 127.0.0.1? - Super User](https://superuser.com/questions/1030329/better-to-block-a-host-to-0-0-0-0-than-to-127-0-0-1)

This behavior is different from Linux which maps 0.0.0.0 to all localhost addresses (or something like that).

**Comment by eaaasun** [comment]
The 1.2.0 final release will fix that. I'll close this issue once it's finished.
