### ISSUE TITLE
[Bug]: Bitdefender terminates CCStopper scripts

### ISSUE THREAD

**Issue by ecbjo** [eaaasun/CCStopper#47]
### What happened?

Stopping the Adobe processes works fine, but Bitdefender Antivirus blocks some things when using it.

- Removing the genuine checker (in v1.1.3)
- Blocking bg processes (in v1.2.0_pre.1)

I've added the whole folder as an exception and even the individual bat scripts. You think there would be any way to resolve this without having to whitelist the windows mshta.exe itself? Attached two screenshots below.

![image](https://user-images.githubusercontent.com/7727007/194759053-855acb0b-3e69-45f3-87a2-e117600931d8.png)
![image](https://user-images.githubusercontent.com/7727007/194759235-6916d287-a993-479c-9b94-ec845aa7e771.png)

### Expected Result?

The scripts should be able to run and finish executing.

### Version?

v1.1.3

### Windows Version?

Windows 10 21H1

**Comment by eaaasun** [comment]
v1.2.0-pre.2 doesn't use mshta.exe; could you try it?

**Comment by eaaasun** [comment]
Try moving it out of your downloads folder; I've had antivirus block scripts coming from there.
