### ISSUE TITLE
[Bug]: The system cannot find the file specified

### ISSUE THREAD

**Issue by niisouu** [eaaasun/CCStopper#49]
### What happened?

When i start the batch file, it shows a quick black screen with few lines saying the same phrase:

_"The system cannot find the file specified
The system cannot find the file specified
The system cannot find the file specified
The system cannot find the file specified"_

after that the CCStopper main screen shows up and when i choose any command nothing happens.

**What should i do??**

### Expected Result?

![Screenshot (8)](https://user-images.githubusercontent.com/115719310/195620087-94105a52-25b9-42f7-ad9f-48ababcb4ac1.png)

### Version?

CCStopper_v1.2.0-pre.2 and CCStopper-Extra_v1.2.0-pre.2

### Windows Version?

Windows 10

**Comment by eaaasun** [comment]
Fixed by replacing `set /p "zoneIdentifier="<"%%a:Zone.Identifier"` with `set zoneIdentifier="<"%%a:Zone.Identifier`

Won't release an update for this issue alone, but you can fix it yourself for now in the CCStopper.bat file.

**Comment by niisouu** [comment]
Hi there, when i applied the edit (and/or used the new released version and its hot fix) it shows the first page and why i use the numbers nothing happens and only the page keeps refreshing. i am lost again!!!
