### ISSUE TITLE
[Bug]: CCStopper closing on launch

### ISSUE THREAD

**Issue by RealDaku** [eaaasun/CCStopper#51]
### What happened?

Everytime i open the CCStopper app, it launches two cmd windows before immediately closing. This has been happening across multiple installations, with the script being launched in administrator.

### Expected Result?

For the CCStopper window to stay open so i can use the scripts as intended.

### Version?

v1.2.0

### Windows Version?

Windows 10 22H2

**Comment by willbert03** [comment]
Open the app in administratior mode and see.

**Comment by A-rhyna-H** [comment]
Getting the same issue

**Comment by Dezzign** [comment]
Yes I get the exact same issue, even running as Admin.

**Comment by ringoz** [comment]
doesn't work on Windows 11

**Comment by eaaasun** [comment]
You might have executions of powershell scripts disabled. The latest release tries to circumvent that but that has not been tested fully. Try going into the "scripts" folder and going into menu.ps1's properties and tick the "unblock" box. If it isn't there, then it's a different issue. 

I would highly recommend against this, but you can also try running `Set-ExecutionPolicy -ExecutionPolicy Unrestricted`. To set the execution policy back to its original, run `Set-ExecutionPolicy Restricted`.
