### ISSUE TITLE
[Bug]: This Unlicensed Adobe App Will Be Disabled Soon message

### ISSUE THREAD

**Issue by SpektacleFR** [eaaasun/CCStopper#56]
### What happened?

The Unlicensed Adobe App popup still continues in some apps; mainly Illustrator and sometimes Photoshop.  It looks something like this:
![image](https://user-images.githubusercontent.com/61282566/218222118-a6738480-cedd-4057-8442-58ca26247377.png)
When Illustrator is blocked completely in the windows defender firewall, this gets disabled.  However, I can not access cloud files then.

### Expected Result?

The Unlicensed app window should never show.  I understand this may not be a CCStopper issue, but CCStopper seems to fix this on other apps such as Photoshop, as aforementioned.

### Version?

1.2.0-Hotfix.1

### Windows Version?

Windows 11 22H2

**Comment by eaaasun** [comment]
I got this with photoshop, my current solution is blocking the app outright with windows firewall but as you stated it'll break cloud files. I'm looking into a more pinpoint solution now.

**Comment by eaaasun** [comment]
Try adding "0.0.0.0 5zgzzv92gn.adobe.io" to your hosts file. It's worked for me with photoshop so I'm considering adding it to the next CCStopper update, but I'd like to see if this fix will work for others.

**Comment by vensauro** [comment]
![image](https://user-images.githubusercontent.com/41435789/227795101-e90da572-0546-4768-930d-be31c9a03714.png)
I'm still with problems dude 
using 1.2.1 version

**Comment by eaaasun** [comment]
The hosts block file is updated regularly, please run the patch again and see if it has any updates. If that doesn't work, you can block `Photoshop.exe` in the firewall.

**Comment by cueboy001** [comment]
> The hosts block file is updated regularly, please run the patch again and see if it has any updates. If that doesn't work, you can block `Photoshop.exe` in the firewall.

This one solve my problem

**Comment by markwheelis** [comment]
Will you get generative fill feature when blocking Photoshop.exe?
