### ISSUE TITLE
[Bug]: HostBlock.ps1 doen't work if the hosts file is already populated

### ISSUE THREAD

**Issue by azumukupoe** [eaaasun/CCStopper#59]
### What happened?

HostBlock.ps1 fails to work when hosts file already has lines of rules from added by https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate

### Expected Result?

hosts file to be updated with the rules

### Version?

v1.2.1

**Comment by eaaasun** [comment]
Could you elaborate on "failed to work?" i.e nothing from CCStopper in the hosts file, a portion of the blocklist in the hosts file, etc.

Also make sure that the whole CCStopper zip is extracted and that you're running CCStopper.bat with admin privileges.

**Comment by eaaasun** [comment]
Sorry for the late reply, but check the permissions of the hosts file. Make sure the 'administrators' group can read/write to the hosts file.
