### ISSUE TITLE
[Bug] InternetBlock Module - Error File Not Found

### ISSUE THREAD

**Issue by GDICK14** [eaaasun/CCStopper#61]
_______________________________________________________________________________
           |                                                                               |
           |                                                                               |
           |                                   CCSTOPPER                                   |
           |                             InternetBlock Module                              |
           |      ___________________________________________________________________      |
           |                                                                               |
           |                            ERROR! FILE NOT FOUND!                             |
           |                                                                               |
           |      Target files could not be found. If the trial prompts are still          |
           |      displayed, please open an issue on the Github repo.                      |
           |      ___________________________________________________________________      |
           |                                                                               |
           |      [Q] Back                                                                 |
           |                                                                               |
           |_______________________________________________________________________________|

Any ideas?

**Comment by eaaasun** [comment]
The current version of CCStopper no longer uses the "InternetBlock" naming for any of its modules, so you may be using an older version/fork of CCStopper. Support for older versions/forks are very limited. Try downloading [the latest version](https://github.com/eaaasun/CCStopper/releases/latest), you will want to use the two modules under "Internet Patches."

Will be closing this issue, please try the latest version and reopen this issue if it persists.

**Comment by eaaasun** [comment]
Just realized that this could be from the official ver of CCStopper, please see #67 for more updates on this issue. Sorry for the confusion!
