### ISSUE TITLE
Unlicensed App Will Be Disabled Soon

### ISSUE THREAD

**Issue by slayerholic666** [eaaasun/CCStopper#68]
Patches stopped working as of today 05/01/23 even after reapplying latest hotfix.

![image](https://user-images.githubusercontent.com/43140269/235465918-42414ce5-371a-480e-bd1c-0c67aff01bf7.png)

**Comment by eaaasun** [comment]
Try running the hosts patch (again), as it gets updated regularly to block new domains that Adobe contacts. There should be a prompt to update when you run it again if you applied it already, or if not, it should work automatically.

**Comment by FlGHT4RACISM** [comment]
Getting this similar pop-up today. Ran ccstopper twice but doesn't seem to fix the pop-up this time. Should I update to the latest photoshop 24.7 or wait? I believe I'm on ver23.xx

**Comment by slayerholic666** [comment]
> Getting this similar pop-up today. Ran ccstopper twice but doesn't seem to fix the pop-up this time. Should I update to the latest photoshop 24.7 or wait? I believe I'm on ver23.xx
> 
> edit: i keep two versions of photoshop just incase and it seems like my 2022 version is unaffected. only my 2023 is having pop-ups.
> 
> edit#2: okay, i found an updated host list off reddit. everything is fine again :)

Glad it was fixed. I've found that reinstalling the program also works, then running the patches again.

**Comment by FlGHT4RACISM** [comment]
> > Getting this similar pop-up today. Ran ccstopper twice but doesn't seem to fix the pop-up this time. Should I update to the latest photoshop 24.7 or wait? I believe I'm on ver23.xx
> > edit: i keep two versions of photoshop just incase and it seems like my 2022 version is unaffected. only my 2023 is having pop-ups.
> > edit#2: okay, i found an updated host list off reddit. everything is fine again :)
> 
> Glad it was fixed. I've found that reinstalling the program also works, then running the patches again.

I'll give that a try next time. What's worked for me is updating the host file manually.

**Comment by Neurotoxin001** [comment]
Adobe changed their license domain
https://www.reddit.com/r/GenP/comments/156qy91/attenzione_unlicensed_pop_up_link_update/

You must block in hosts this: `1hzopx6nz7.adobe.io`

**Comment by coeyes** [comment]
It looks like the following domains have also been added recently
```
23ynjitwt5.adobe.io
```

**Comment by huckleberrypie** [comment]
Try the following domains:
`0.0.0.0 guzg78logz.adobe.io
127.0.0.1 guzg78logz.adobe.io
127.0.0.1 ic.adobe.io
127.0.0.1 b5kbg2ggog.adobe.io
127.0.0.1 p13n.adobe.io
127.0.0.1 7sj9n87sls.adobe.io
127.0.0.1 ij0gdyrfka.adobe.io
127.0.0.1 23ynjitwt5.adobe.io`

**Comment by reddit-reaper** [comment]
and thats why firewall patching all the adobe directories is just easier lol

**Comment by WlSDXM** [comment]
nah, firewall blocking is not necessary anymore if you're using the patch CC powershell method + GenP

**Comment by t4rra** [comment]
[CCStopper is being sunset.](https://github.com/eaaasun/CCStopper#migrating-fromuninstalling-ccstopper-) I recommend looking through the [listed alternatives](https://github.com/eaaasun/CCStopper#alternatives) if things still don't work.
