### ISSUE TITLE
[Issue]: Unable to add to Host file

### ISSUE THREAD

**Issue by FlGHT4RACISM** [eaaasun/CCStopper#71]
### What happened?

https://postimg.cc/K3hzLKQV   image of whats happening. ccstopper will state everything went fine right after when i don't think thats the case.

I've used CCStopper before and things went great. But tonight for some reason I am no longer able to patch host file for some reason. It's being denied. It worked before, I'm not sure what changed. 

EDIT: This is happening after I agree (press 1) to grant access to write host file. 

### Expected Result?

CCStopper - Access to write host file 

### Version?

1.22. hotfix 1

### Windows Version?

latest wins 11 (may update)

**Comment by eaaasun** [comment]
The permissions for the hosts file might have changed/reset after an update. I haven't tested the "grant access to hosts file" option much as it's an issue I rarely face. I'll look into it soon. You can go into the properties of the file, and under the security tab, grant the 'Administrators' group full permissions.

**Comment by eaaasun** [comment]
I just released the v1.2.3-pre.2 (formerly v1.3.0-pre.x) update. It changes the way file permissions are handled so that the module gives itself the permission, writes what it needs, and then restores the permission change.

**Comment by FlGHT4RACISM** [comment]
> I just released the v1.2.3-pre.2 (formerly v1.3.0-pre.x) update. It changes the way file permissions are handled so that the module gives itself the permission, writes what it needs, and then restores the permission change. Please give it a try and let me know.

thank you! just downloaded it. I managed to fix my earlier issue by adding to the host file manually. thank you again for your great work! i very much appreciate it ^_^
