### ISSUE TITLE
[Bug]:  Doesnt work

### ISSUE THREAD

**Issue by veryrareflicks** [eaaasun/CCStopper#72]
### What happened?

CCStopper stopped working. When I run it and choose the options that are needed, and then try to install Photoshop, it still won't work.

### Expected Result?

Cloud

### Version?

v1.2.2-hotfix.1

### Windows Version?

Windows 10

**Comment by eaaasun** [comment]
From the level of detail you provided, it doesn't seem like an issue with CCStopper. Check with the appropriate subreddits/discord servers for the use of other applications for 'cracking' Adobe apps.

**Comment by alanxummp** [comment]
works for me, genuine adobe user here.
