### ISSUE TITLE
[Bug]: Closing on launch

### ISSUE THREAD

**Issue by plnsty** [eaaasun/CCStopper#73]
### What happened?

When im opening the app it closes, i tried everything that i could
need help asap

### Expected Result?

.

### Version?

latest

### Windows Version?

windows 10 21h2

**Comment by eaaasun** [comment]
Make sure to extract all files and make sure [running powershell scripts are enabled](https://superuser.com/a/106362). Can't offer much more help as details provided are minimal.

**Comment by eaaasun** [comment]
Also will be closing this issue as this is a duplicate of #51.
