### ISSUE TITLE
[Bug]: CC Install button patcher won't work anymore

### ISSUE THREAD

**Issue by SupahFox** [eaaasun/CCStopper#78]
### What happened?

When I try to patch Creative Cloud, it just says that it's corrupt and needs to reinstall it.
Already reinstalled it using Adobe's CC Cleaner Tool.

### Expected Result?

CC opening normally with the Install button patched.

### Version?

v1.2.3-pre.1

### Windows Version?

Windows 11 22H2

**Comment by eaaasun** [comment]
The new CC update breaks this patch, I recommend you look on the genP discord (in the tips and guides channel) for the PowerShell commands that work with the new version.

**Comment by SupahFox** [comment]
> The new CC update breaks this patch, I recommend you look on the genP discord (in the tips and guides channel) for the PowerShell commands that work with the new version.

Pwsh commands won´t work also. Guess we'll have to wait for the patch

**Comment by eaaasun** [comment]
Just updated, please try v1.2.3-pre.2 (formerly v1.3.0-pre.x)

**Comment by SupahFox** [comment]
Got it
