### ISSUE TITLE
[Bug]: Ccstopper closing as soon as I open it

### ISSUE THREAD

**Issue by mynameisjonass** [eaaasun/CCStopper#85]
### What happened?

As soon as I run the batch file it asks for admin privileges, opens a few windows really fast, then closes. I've tried running every script individually, enabling allow powershell scripts rule, turning defender on and off, moving files to C: drive, enabling everything in TEMP and ccstopper folders, but nothing works. Sorry for making another duplicate thread but I've been ripping my hair out with this problem the past few days and nothing said in those other threads have helped whatsoever.

### Expected Result?

To be able to access the ccstopper menu

### Version?

v1.2.3-hotfix.1

### Windows Version?

10

### Duplicate Issues

- [X] I have read through the issues and have not found a duplicate.

**Comment by eaaasun** [comment]
Honestly, I'm not sure what went wrong here. You've tried all the things I would've haha

Out of curiosity, has this been happening on both the zip (from the releases) and the one-line commands?

**Comment by mynameisjonass** [comment]
> Honestly, I'm not sure what went wrong here. You've tried all the things I would've haha
> 
> Out of curiosity, has this been happening on both the zip (from the releases) and the one-line commands?

yes it has
