### ISSUE TITLE
[Bug]: Missing firewall rules in v1.2.3 hotfix1

### ISSUE THREAD

**Issue by teijiIshida** [eaaasun/CCStopper#86]
### What happened?

There was an option to add firewall rules to block inbound/outbound rules for Adobe apps in previous version, but it was not in v1.2.3.

### Expected Result?

Option to add firewall rules to block inbound/outbound rules for Adobe apps.

### Version?

1.2.3 hotfix1

### Windows Version?

Windows 2H22

### Duplicate Issues

- [X] I have read through the issues and have not found a duplicate.

**Comment by eaaasun** [comment]
I've removed the firewall option after many reports of it failing/being unnecessary, and in my own testing, the CC App patch + Hosts work just as well, if not better. I'd recommend you give that a try and please let me know how it goes.

**Comment by teijiIshida** [comment]
Ah ok. Just wondering if it was intentional removal or maybe you forgot. Now, I know. I can manually do the firewall rules myself. 

Thanks for the scripts.
