### ISSUE TITLE
[Bug]: CCStopper not allowing for inputs

### ISSUE THREAD

**Issue by johnson4423** [eaaasun/CCStopper#87]
### What happened?

First few times opening the program, it operated as expected however didn't work to allow access to the cloud even though all steps were followed. Now when I try to use it, pressing the numbers to select each action simply moves the cursor through the whole screen and does nothing. Preessing Q works to exit the program and it seems to register the numbers but doesn't leave the home screen. 

### Expected Result?

Closes adobes background processes

### Version?

V 1.2.3-hotfix 1

### Duplicate Issues

- [X] I have read through the issues and have not found a duplicate.

**Comment by eaaasun** [comment]
Hmm I've never seen this issue before. Did you download the zip file (from the releases) or run it from the one-line commands? If you downloaded it, Powershell might be blocking the scripts due to the execution policy.

In Powershell, you can try running `Set-ExecutionPolicy Unrestricted`, then run CCStopper. Afterwards, make sure to run `Set-ExecutionPolicy Restricted`.

**Comment by reddit-reaper** [comment]
seen this lol dont use numpad, use numbers on top row of keyboard...idk why but when using numpad for me on any pc it just doesnt work

**Comment by eaaasun** [comment]
That's a really interesting issue... I don't use a numpad normally but I'll take a look into it!

**Comment by Slibzz** [comment]
I had to launch using :  powershell -ExecutionPolicy Unrestricted -File .\scripts\Menu.ps1 and not use numpad to fix closing immediatly and the menu is simply not working using the numpad.

**Comment by t4rra** [comment]
[CCStopper is being sunset.](https://github.com/eaaasun/CCStopper#migrating-fromuninstalling-ccstopper-) I still don't really know why a numpad isn't working, and unfortunately I won't be able to research more/fix it. I suggest you take a look at the [listed alternatives](https://github.com/eaaasun/CCStopper#alternatives) for methods that work after CCStopper is sunset (also they probably won't need a numpad input lol).
