### ISSUE TITLE
Doesn't appear to be working anymore

### ISSUE THREAD

**Issue by K9Paradox** [eaaasun/CCStopper#9]
The latest version was downloaded, but it isn't ending the process. Ran as admin.

**Comment by E-Soda** [comment]
Windows won't run scripts downloaded from the internet, manually running the "processkill.ps1" script from the "scripts" folder for the first time should fix this problem. After that, running the ccstopper script normally should work fine.

**Comment by K9Paradox** [comment]
Run with powershell? I tried and still isn't closing any processes ;-;

**Comment by E-Soda** [comment]
You can also try running `set-executionpolicy remotesigned` in an admin powershell window.

**Comment by K9Paradox** [comment]
I've tried everything. The processes stay active.

**Comment by E-Soda** [comment]
Unfortunately, I cannot recreate this issue on my device, I also forgot to mention that you need to extract all files, don't run the script directly from the zip folder as it needs the additional scripts in the `scripts` folder.

**Comment by K9Paradox** [comment]
Yes I am aware, the folder is extracted, tried running the script file via poweshell individually. Tried running both .bat files as admin, they open, but when selecting 1, or the button to end the processes a window pops up for about half a second as if it is doing something but the processes are still running.

**Comment by K9Paradox** [comment]
https://drive.google.com/drive/folders/1AbWXk7ZCxhGI6jdp59LUoRehZri-5EiQ?usp=sharing

**Comment by E-Soda** [comment]
Don't run the .bat scripts as administrator, it'll automatically prompt you if it needs admin access.

**Comment by K9Paradox** [comment]
Well, same result if they aren’t run as admin.

**Comment by AmodeusR** [comment]
I have the same problem :/

**Comment by Gitlish** [comment]
I had the same problem as above – **End Adobe Processes** did nothing at all. However, works fine _after_ running **Remove AGS**.

**Comment by speedypotato** [comment]
Ran into the same issue.  Opening powershell by itself and trying to execute the script I got a "running scripts is disabled".  This is a fresh install of windows on a brand new machine.  Followed the steps here: https://www.repairwin.com/fix-running-scripts-disabled-on-windows-10/ and ran CCStopper.bat again and seems to work now.

**Comment by ginkgog** [comment]
any fix for acrobat version 21.011.20039? as the pop-up blocked the usage of the tools.
<img width="532" alt="Capturesdf" src="https://user-images.githubusercontent.com/98633052/151648670-1de92cac-93ee-4e61-8012-5586030098e1.PNG">

**Comment by eaaasun** [comment]
https://www.reddit.com/r/GenP/comments/qgts31/update_compatibility_list_2022_creative_suite/ 
I don't think acrobat is patched yet; I don't have a fix, unfortunately.
