### ISSUE TITLE
After running CCStopper | Adobe Creative cloud desktop is not loading (Stuck on initializing creative cloud)

### ISSUE THREAD

**Issue by Capsky1** [eaaasun/CCStopper#91]
![image](https://github.com/eaaasun/CCStopper/assets/142726114/3f7fc1ce-5641-40ef-aed1-bc9d2454c1c3)

Can you please advise if I can revert CCStopper and then run it again after adding the required adobe apps.

**Comment by eaaasun** [comment]
Yes, you can reverse it by running the module again.

**Comment by ashbrush108** [comment]
Which option should I choose in CCStopper to revert?

**Comment by eaaasun** [comment]
Which modules did you run before?

**Comment by ashbrush108** [comment]
yea I ran CCblocker..there is no option in it to unblock it seems

**Comment by eaaasun** [comment]
Run the same modules as if you were to apply them. They will detect if it's been applied and offer to reverse it.

**Comment by saberslayer221** [comment]
even after i reverse it still doesnt work

**Comment by JSBmanD** [comment]
I have the same issue, reversing/uninstalling/cleaning with adobe tool doesn't work.

**Comment by NotaInutilis** [comment]
Same issue on Creative Cloud version 6.1.0.587. Reverting the Creative Cloud Apps trial button patch fixes the problem and loads the CC app, albeit with trial buttons. The hosts patch causes no issue.

**Comment by t4rra** [comment]
[CCStopper is being sunset.](https://github.com/eaaasun/CCStopper#migrating-fromuninstalling-ccstopper-) I recommend reverting the CC App patch (manually if CCStopper isn't working) and use the listed alternative in the README. A restart might be required before changes apply. If all else fails, you might have to reinstall Creative Cloud.
