### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lechinskee** [eaaasun/CCStopper#93]
### What happened?

ccstopper just not working with the latest creative cloud update :'(

### Expected Result?

how can i fix it?

### Version?

v1.2.3-hotfix.1

### How did you use CCStopper?

One-Line - Run

### Windows Version?

windows 10

### Duplicate Issues

- [X] I have read through the issues and have not found a duplicate.

**Comment by eaaasun** [comment]
What doesn't work? If it's the trial buttons, I've updated that so that it works with the new CC app update.

**Comment by lechinskee** [comment]
yess, thank you! sorry for my english (i'm brazillian), what was happening is that creative cloud was updated and CCStopper was no longer working, i don't know why exactly but im try again righ now

**Comment by eaaasun** [comment]
Again, I don't know what isn't working for you. I'll be closing this issue, you can re-open this issue by leaving another comment.
