### ISSUE TITLE
[Feature]: Deactivating unnecessary background processes

### ISSUE THREAD

**Issue by NotaInutilis** [eaaasun/CCStopper#95]
### What do you want to see added?

Hi! Thanks for your work! It works well and is easy to use.

Recently, I've used this tutorial https://www.reddit.com/r/GenP/wiki/redditgenpguides/#wiki_.25BA_guide_.238_-_blocking_unnecessary_adobe_background_processes.28ps.2Fdc.29 to completely deactivate a few adobe processes which still ran automatically at startup. Would it be possible to add this to CCStopper?

I see that this was previously implemented last year https://github.com/eaaasun/CCStopper/pull/29 but it seems like this script has now disappeared from the repo. Was there a problem with it?

### How could this be accomplished?

Add a `.bak` to the name of the following files (and allow to reverse it).

```
C:\Program Files (x86)\Adobe\Adobe Sync\CoreSync\CoreSync.exe
C:\Program Files\Adobe\Adobe Creative Cloud Experience\CCXProcess.exe
C:\Program Files\Common Files\Adobe\Creative Cloud Libraries\CCLibrary.exe
C:\Program Files\Adobe\Acrobat DC\Acrobat\AdobeCollabSync.exe
```

The following file is needed for CC update so we'd need another solution.
`C:\Program Files (x86)\Common Files\Adobe\Adobe Desktop Common\ADS\Adobe Desktop Service.exe`

### Duplicate Feature Request

- [X] I have checked the issues section and there are no duplicates.

**Comment by eaaasun** [comment]
I've found that there's not much impact by disabling the above files, plus I'm trying to avoid a bloated list of options that a handful of users would find useful once. 

There wasn't a problem with the pull request, and I believe [that script](https://github.com/eaaasun/CCStopper/blob/219d6354324ea266681c8ed5e92806ab921c004b/scripts/RenameFiles.bat) can be run standalone (which isn't the case for current modules). I only decided to remove it for the above reasons.
