### ISSUE TITLE
[Feature]: disable auto-update

### ISSUE THREAD

**Issue by NotaInutilis** [eaaasun/CCStopper#96]
### What do you want to see added?

A script to disable auto-updating in CC and Acrobat.

It was re-enabled when I last updated both, so instead of going to check in the menus, it'd be easier to just run a script.

### How could this be accomplished?

Hopefully, simply by changing a `true` to a `false` in a couple of configuration files. I tried to locate them (in AppData, ProgramData and registry) but wasn't able to find where they're stored.

### Duplicate Feature Request

- [X] I have checked the issues section and there are no duplicates.

**Comment by t4rra** [comment]
[CCStopper is being sunset. Enhancements will not be worked on.](https://github.com/eaaasun/CCStopper#migrating-fromuninstalling-ccstopper-)
