### ISSUE TITLE
[Feature]: Run at start up with Task Scheduler

### ISSUE THREAD

**Issue by AdKiller** [eaaasun/CCStopper#98]
### What do you want to see added?

Since the Adobe background tasks keep coming back, I would like to run the .bat file at startup with Task Scheduler. Is that possible?

### Duplicate Feature Request

- [X] I have checked the issues section and there are no duplicates.

**Comment by t4rra** [comment]
[CCStopper is being sunset. Enhancements will not be worked on.](https://github.com/eaaasun/CCStopper#migrating-fromuninstalling-ccstopper-)
